### ISSUE TITLE
Innledende fase (koordinerende issue)

### ISSUE THREAD

**Issue by torgeirl** [cybernetisk/cyb50-hefte#1]
Innen utgangen av mai skal @megoth og @torgeirl ha den overordnede strukturen klar.

Der man trenger ting fra andre blir det i stor grad opprettet egne issues på denne milestonen- dette issuet er hovedsakelig ment for å koordinere arbeidet utover hva man skriver internt på Slack.

**Comment by megoth** [comment]
Note to self: Finn forfattere til tekster vi ønsker å ha med i jubileumsheftet (jf https://github.com/cybernetisk/cyb50-hefte/wiki/M%C3%B8te-2018.04.17)
